app/assign_students/models.py
from app import db

class Assign_Students(db.Model):
    __tablename__ = "assign_students"
    id = db.Column(db.Integer, primary_key = True)
    student_id = db.Column(db.Integer, db.ForeignKey("student.id"), nullable = False)
    group_id = db.Column(db.Integer, db.ForeignKey("group.id"), nullable = False)

    student = db.relationship("Student", backref = "assign_student")
    group = db.relationship("Group", backref = "assign_student")

    def __repr__(self):
        return f"<Assign_Students>{self.name}"

app/assign_students/forms.py
from flask_wtf import *
from wtforms import *
from wtforms.validators import *
from app.student.models import Student
from app.group.models import Group

class AssignStudentForm(FlaskForm):
    id = HiddenField("id")
    student_id = SelectField("Select Student")
    group_id = SelectField("Select Group")
    submit = SubmitField("Save Changes")

    def __init__(self, *args, **kwargs):
        super(AssignStudentForm, self).__init__(*args, **kwargs)
        self.student_id.choices = [(student.id, student.name)for student in Student.query.all()]
        self.group_id.choices = [(group.id, group.name)for group in Group.query.all()]

app/assign_students/__init__.py
from flask import Blueprint

assign_students_bp = Blueprint("assign_students", __name__, template_folder = "templates", static_folder = "static")

from app.assign_students import views

app/assign_students/views.py
from flask import *
from app.assign_students import assign_students_bp
from app.assign_students.models import Assign_Students
from app.assign_students.forms import AssignStudentForm
from app import db

@assign_students_bp.route("/assign_students_list")
def get_assign_students_to_group_list():
    assign_student = Assign_Students.query.all()
    return render_template("list_assign_students.html", ass = assign_student)

@assign_students_bp.route("/add_assign_student", methods = ["GET", "POST"])
def add_assign_student():
    forms = AssignStudentForm()
    if forms.validate_on_submit():
        student_id = forms.student_id.data
        group_id = forms.group_id.data

        new_assign_student = Assign_Students(student_id = student_id, group_id = group_id)
        db.session.add(new_assign_student)
        db.session.commit()
        return redirect(url_for("assign_students.get_assign_students_to_group_list"))

    return render_template("add_assign_student.html", form = forms)

@assign_students_bp.route("/update_assign_student/<int:id>", methods = ["GET", "POST"])
def update_assign_student(id):
    assign_student = Assign_Students.query.get_or_404(id)
    form = AssignStudentForm(obj = assign_student)
    if form.validate_on_submit():
        form.populate_obj(assign_student)
        db.session.commit()
        return redirect(url_for("assign_students.get_assign_students_to_group_list"))
    return render_template("add_assign_student.html", form = form)

@assign_students_bp.route("/delete_assign_student/<int:id>", methods = ["POST"])
def delete_assign_student(id):
    assign_student = Assign_Students.query.get_or_404(id)
    db.session.delete(assign_student)
    db.session.commit()
    return redirect(url_for("assign_students.get_assign_students_to_group_list"))

@assign_students_bp.route("/delete_all_assign_students", methods = ["POST"])
def delete_all_assign_students():
    Assign_Students.query.delete()
    db.session.commit()
    return redirect(url_for("assign_students.get_assign_students_to_group_list"))

app/assign_students/templates/add_assign_student.html
{% extends "index.html" %}

{% block title %} Add Assign Student {% endblock %}

{% block content %}
<div class="formContainer">
    <form method="POST" class="writingForm">
        <h2 class="formHead">Enter or Edit Details</h2>
        <p>
            {{form.hidden_tag()}}
        </p>
        
        <p>
            {{form.student_id.label(class = "label")}}
            <br>
            {{form.student_id(class = "scrolling")}}
        </p>
    
        <p>
            {{form.group_id.label(class = "label")}}
            <br>
            {{form.group_id(class = "scrolling")}}
        </p>
        
        <p>
            {{form.submit(class = "submitButton")}}
        </p>
    </form>
</div>


{% endblock %}

app/assign_students/templates/list_assign_students.html
{% extends "index.html" %}

{% block title %} Assign Students List {% endblock %}

{% block content %}

    <h1>Welcome to Assign Students List</h1>
    <p class="description">This page contains all the records about the various students in various groups in the school. The records can also be updated and deleted here</p>
    <br>
    <div class="table">
        <a class="btn-grad" href="{{url_for('assign_students.add_assign_student')}}">Add Assignments</a>&nbsp;

        <form method="POST" action="{{url_for('assign_students.delete_all_assign_students')}}">
            <button type="submit" onclick="return confirm('Are you sure that you want to delete all student assignments')" href = "#" class="btn-grad-delete">Delete all Assignments</button>
        </form>
        
    </div>
    <br>
    <div> 
        <table>
            <tr>
                <th>S/N</th>
                <th>Student Name</th>
                <th>Student Code</th>
                <th>Group Name</th>
                <th>Group Code</th>
                <th>Action</th>
            </tr>
            {% for i in ass%}
            <tr class="row">
                <td> {{i.id}} </td>
                <td> {{i.student.name}} </td>
                <td> {{i.student.code}} </td>
                <td> {{i.group.name}} </td>
                <td> {{i.group.code}} </td>
                <td><a class="button_primary", href="{{url_for('assign_students.update_assign_student', id = i.id)}}">Edit</a>&nbsp;
                    <form method="POST" action = "{{url_for('assign_students.delete_assign_student', id = i.id)}}">
                        <button type="submit" onclick="return confirm('Are you sure that you want to delete this student assignment')">Delete</button>
                    </form>
            </tr>
            {% endfor %}
        </table>
    </div>   <br>

{% endblock %}