app/course/models.py
from app import db

class Course(db.Model):
    __tablename__ = "course"
    id = db.Column(db.Integer, primary_key = True)
    program_id = db.Column(db.Integer, db.ForeignKey("program.id"), nullable = False)
    level_id = db.Column(db.Integer, db.ForeignKey("level.id"), nullable = False)
    name = db.Column(db.String(50), nullable = False, unique = True)
    code = db.Column(db.String(10), nullable = False, unique = True)

    program = db.relationship("Program", backref = "course")
    level = db.relationship("Level", backref = "course")

    def __repr__(self):
        return f"<Course>{self.name}"

app/course/forms.py
from flask_wtf import *
from wtforms import *
from wtforms.validators import *
from app.program.models import Program
from app.level.models import Level

class CourseForm(FlaskForm):
    id = HiddenField("id")
    program_id = SelectField("Select Program")
    level_id = SelectField("Select Level")
    name  = StringField("Course Name:", validators = [DataRequired()])
    code  = StringField("Course Code:", validators = [DataRequired()])
    submit = SubmitField("Save Changes")

    def __init__(self, *args, **kwargs):
        super(CourseForm, self).__init__(*args, **kwargs)
        self.program_id.choices = [(program.id, program.name)for program in Program.query.all()]
        self.level_id.choices = [(level.id, level.name)for level in Level.query.all()]

app/course/__init__.py
from flask import Blueprint

course_bp = Blueprint("course", __name__, template_folder = "templates", static_folder = "static")

from app.course import views

app/course/views.py
from flask import *
from app.course import course_bp
from app.course.models import Course
from app.course.forms import CourseForm
from app import db

@course_bp.route("/course_list", methods = ["GET"])
def get_course_list():
    course = Course.query.all()
    return render_template("list_course.html", cs = course)

@course_bp.route("/add_course", methods = ["GET", "POST"])
def add_courses():
    forms = CourseForm()
    if forms.validate_on_submit():
        program_id = forms.program_id.data
        level_id = forms.level_id.data
        course_name = forms.name.data
        course_code = forms.code.data

        new_course = Course(program_id = program_id, level_id = level_id, name = course_name, code = course_code)
        db.session.add(new_course)
        db.session.commit()
        return redirect(url_for("course.get_course_list"))

    return render_template("add_course.html", form = forms)

@course_bp.route("/update_course/<int:id>", methods = ["GET", "POST"])
def update_course(id):
    course = Course.query.get_or_404(id)
    form = CourseForm(obj = course)
    if form.validate_on_submit():
        form.populate_obj(course)
        db.session.commit()
        return redirect(url_for("course.get_course_list"))
    return render_template("add_course.html", form = form)

@course_bp.route("/delete_course/<int:id>", methods = ["POST"])
def delete_course(id):
    course = Course.query.get_or_404(id)
    db.session.delete(course)
    db.session.commit()
    return redirect(url_for("course.get_course_list"))

@course_bp.route("/delete_all_courses", methods = ["POST"])
def delete_all_courses():
    Course.query.delete()
    db.session.commit()
    return redirect(url_for("course.get_course_list"))

app/course/templates/add_course.html
{% extends "index.html" %}

{% block title %} Add Course {% endblock %}

{% block content %}

<div class="formContainer">
    <form method="POST" class="writingForm">
        <h2 class="formHead">Enter or Edit Details</h2>

        <p>
            {{form.hidden_tag()}}
        </p>
        
        <p>
            {{form.program_id.label(class = "label")}}
            <br>
            {{form.program_id(class = "scrolling")}}
        </p>
    
        <p>
            {{form.level_id.label(class = "label")}}
            <br>
            {{form.level_id(class = "scrolling")}}
        </p>
    
        <p>
            {{form.name.label(class = "label")}}
            <br>
            {{form.name(class = "filling")}}
        </p>
        
        <p>
            {{form.code.label(class = "label")}}
            <br>
            {{form.code(class = "filling")}}
        </p>
        
        <p>
            {{form.submit(class = "submitButton")}}
        </p>
    </form>
    
</div>

{% endblock %}

app/course/templates/list_course.html
{% extends "index.html" %}

{% block title %} Course List {% endblock %}

{% block content %}

    <h1>Welcome to Course List</h1>
    <p class="description">This page contains all the records about the various courses in the school. The records can also be updated and deleted here</p>
    <br>
    <div class="table">
        <a class="btn-grad" href="{{url_for('course.add_courses')}}">Add Course</a>&nbsp;

        <form method="POST" action="{{url_for('course.delete_all_courses')}}">
            <button type="submit" onclick="return confirm('Are you sure that you want to delete all courses')" href = "#" class="btn-grad-delete">Delete all Courses</button>
        </form>
        
    </div>

    <br>

    <div> 
        <table>
            <tr>
                <th>S/N</th>
                <th>Level ID</th>
                <th>Level Name</th>
                <th>Program ID</th>
                <th>Program Name</th>
                <th>Course Name</th>
                <th>Course Code</th>
                <th>Action</th>
            </tr>

            {% for i in cs%}
            <tr class="row">
                <td> {{i.id}} </td>
                <td> {{i.level.id}} </td>
                <td> {{i.level.name}} </td>
                <td> {{i.program.id}} </td>
                <td> {{i.program.name}} </td>
                <td> {{i.name}} </td>
                <td> {{i.code}} </td>
                <td><a class="button_primary", href="{{url_for('course.update_course', id = i.id)}}">Edit</a>&nbsp;
                    <form method="POST" action = "{{url_for('course.delete_course', id = i.id)}}">
                        <button type="submit" onclick="return confirm('Are you sure that you want to delete this course')">Delete</button>
                    </form>
            </tr>
            {% endfor %}
        </table>
    </div>   <br>

{% endblock %}