app/group/models.py
from app import db

class Group(db.Model):
    __tablename__ = "group"
    id = db.Column(db.Integer, primary_key = True)
    name = db.Column(db.String(50), nullable = False, unique = True)
    code = db.Column(db.String(10), nullable = False, unique = True)

    def __repr__(self):
        return f"<Group>{self.name}"

app/group/forms.py
from flask_wtf import *
from wtforms import *
from wtforms.validators import *

class GroupForm(FlaskForm):
    id = HiddenField("id")
    name  = StringField("Group Name:", validators = [DataRequired()])
    code  = StringField("Group Code:", validators = [DataRequired()])
    submit = SubmitField("Save Changes")

app/group/__init__.py
from flask import Blueprint

group_bp = Blueprint("group", __name__, template_folder = "templates", static_folder = "static")

from app.group import views

app/group/views.py
from flask import *
from app.group import group_bp
from app.group.forms import GroupForm
from app.group.models import Group
from app import db

@group_bp.route("/group_list", methods = ["GET"])
def get_group_list():
    group = Group.query.all()
    return render_template("list_group.html", gp = group)

@group_bp.route("/add_group", methods = ["GET", "POST"])
def add_group():
    forms = GroupForm()
    if forms.validate_on_submit():
        group_name = forms.name.data
        group_code = forms.code.data

        new_group = Group(name = group_name, code = group_code)
        db.session.add(new_group)
        db.session.commit()
        return redirect(url_for("group.get_group_list"))

    return render_template("add_group.html", form = forms)

@group_bp.route("/delete_group/<int:id>", methods = ["POST"])
def delete_group(id):
    group = Group.query.get_or_404(id)
    db.session.delete(group)
    db.session.commit()
    return redirect(url_for("group.get_group_list"))

@group_bp.route("/edit_group/<int:id>", methods = ["GET", "POST"])
def update_group(id):
    group = Group.query.get_or_404(id)
    form = GroupForm(obj = group)
    if form.validate_on_submit():
        form.populate_obj(group)
        db.session.commit()
        return redirect(url_for("group.get_group_list"))
    return render_template("add_group.html", form = form)

@group_bp.route("/delete_all_group", methods = ["POST"])
def delete_all_group():
    Group.query.delete()
    db.session.commit()
    return redirect(url_for("group.get_group_list"))

app/group/templates/add_group.html
{% extends "index.html" %}

{% block title %} Add Group {% endblock %}

{% block content %}
<div class="formContainer">
    <form method="POST" class="writingForm">
        <h2 class="formHead">Enter or Edit Details</h2>
        <p>
            {{form.hidden_tag()}}
        </p>
        
        <p>
            {{form.name.label(class = "label")}}
            <br>
            {{form.name(class = "filling")}}
        </p>
        
        <p>
            {{form.code.label(class = "label")}}
            <br>
            {{form.code(class = "filling")}}
        </p>
        
        <p>
            {{form.submit(class = "submitButton")}}
        </p>
    </form>
</div>


{% endblock %}

app/group/templates/list_group.html
{% extends "index.html" %}

{% block title %} Group List {% endblock %}

{% block content %}

    <h1>Welcome to Group List</h1>
    <p class="description">This page contains all the records about the various groups in the school. The records can also be updated and deleted here</p>
    <br>
    <div class="table">
        <a class="btn-grad" href="{{url_for('group.add_group')}}">Add Group</a>&nbsp;

        <form action="{{url_for('group.delete_all_group')}}" method="POST">
            <button type="submit" onclick="return confirm('Are you sure that you want to delete all groups')" href = "#" class="btn-grad-delete">Delete all Groups</button>
        </form>
        
    </div>
    <br>
    <div> 
        <table>
            <tr>
                <th>S/N</th>
                <th>Group Name</th>
                <th>Group Code</th>
                <th>Action</th>
            </tr>

            {% for i in gp %}
            <tr class="row">
                <td> {{i.id}} </td>
                <td> {{i.name}} </td>
                <td> {{i.code}} </td>
                <td><a class="button_primary", href="{{url_for('group.update_group', id = i.id)}}">Edit</a>&nbsp;
                    <form action="{{url_for('group.delete_group', id = i.id)}}" method="POST">
                        <button type="submit" onclick="return confirm('Are you sure that you want to delete this group')">Delete</button>
                    </form>
            </tr>
            {% endfor %}
        </table>
    </div>   <br>

{% endblock %}